services:
  barhelperfrontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.reactUI
    ports:
      - "8080:8080"    
    depends_on:
      - db
  nodebackend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile.node
    ports: 
      - "9000:9000"    
    depends_on:
      - db
  db:
    volumes:
      - inventory_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
volumes:
   inventory_db: