services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.reactUI
    image: 
      rjzhang100/robson-bar-helper:FEv1
    ports:
      - "8080:8080"    
    depends_on:
      - db
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile.node
    environment:
      - ATLAS_URI=mongodb+srv://rjzhang100:omrf1yAUcl273Lvg@cluster0.j3lsalz.mongodb.net/test
    ports: 
      - "9000:9000"    
    image: 
      rjzhang100/robson-bar-helper:BEv1
    depends_on:
      - db
  db:
    volumes:
      - inventory_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  

volumes:
   inventory_db: