FROM node:16
WORKDIR /app
COPY ./package.json ./package.json
COPY ./server.js ./server.js
COPY ./routes.js ./routes.js
COPY ./db/conn.js ./db/conn.js
RUN yarn install 
EXPOSE 9000
CMD ["node", "server.js"]